# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.35.0-standalone/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-router-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agent-sandbox-router.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.router.replicaCount }}
  selector:
    matchLabels:
      {{- include "agent-sandbox-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agent-sandbox-router.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.router.securityContext.runAsUser }}
        runAsGroup: {{ .Values.router.securityContext.runAsGroup }}
      containers:
        - name: router
          image: "{{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}"
          imagePullPolicy: {{ .Values.router.image.pullPolicy }}
          env:
            {{- toYaml .Values.router.env | nindent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            {{- toYaml .Values.router.resources | nindent 12 }}
